<a href="https://colab.research.google.com/github/neerajthandayan/Deep_Learning/blob/main/Artificial%20Neural%20Networks/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Artificial Neural Networks

###### Importing Libraries

In [63]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [64]:
tf.__version__

'2.4.1'

#### Part - 1: Data Pre-processing 

###### Importing Datasets

In [65]:
data = pd.read_csv("https://raw.githubusercontent.com/neerajthandayan/Deep_Learning/main/Artificial%20Neural%20Networks/Churn_Modelling.csv")

In [66]:
data.head(10)

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0
5          6    15574012       Chu  ...               0       149756.71      1
6          7    15592531  Bartlett  ...               1        10062.80      0
7          8    15656148    Obinna  ...               0       119346.88      1
8          9    15792365        He  ...               1        74940.50      0
9         10    15592389        H?  ...               1        71725.73      0

[10 rows x 14 columns]

In [67]:
data.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [68]:
data.drop(columns= ['RowNumber', 'CustomerId', 'Surname'], inplace= True)

In [69]:
# Creating IV(Matrxi of Features) and DV

X = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

#### Encoding Categorical Variables

In [70]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

# Label Encoding Gender Column
X[:,2] = le.fit_transform(X[:,2])

In [71]:
# One hot encoding for Geography column

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [72]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

###### Creating Training & Test Sets

In [73]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 41)

###### Feature Scaling

In [74]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)

# Only Transform is done in test set to avoid data leakage
X_test = sc.transform(X_test)

#### Part - 2: Building ANN

###### Initialising ANN

In [75]:
ann = tf.keras.models.Sequential()

###### Adding Input Layer and First Hidden Layer

In [76]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu',))

###### Adding Second Hidden Layer

In [77]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu',))

###### Adding Output Layer

In [78]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid',))

#### Part - 3: Training The ANN

##### Compiling The ANN

In [79]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

###### Training the ANN on the Training Set

In [80]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.7913 - accuracy: 0.3969
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5233 - accuracy: 0.7948
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4637 - accuracy: 0.7952
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4353 - accuracy: 0.8045
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4333 - accuracy: 0.8096
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4048 - accuracy: 0.8331
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3968 - accuracy: 0.8372
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3843 - accuracy: 0.8427
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3634 - accuracy: 0.8546
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3584 - accura

#### Part - 4: Making Prediction and Evaluating Models

In [81]:
# Random Prediction

ann.predict(sc.transform([[1.0, 0.0, 0.0,600,1,40,3,60000,2,1,1,50000,]])) > 0.5

array([[False]])

In [82]:
# Checking Test Set Prediction

ypred = ann.predict(X_test) > 0.5
ypred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [83]:
# Making a confusion Matrix

from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, ypred)
acc = accuracy_score(y_test, ypred)

print(cm)
print(f"The accuracy of the model is: {round(acc*100,2)}")

[[1538   59]
 [ 210  193]]
The accuracy of the model is: 86.55
